AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Stage:
    Type: String
Resources:
  ContactFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: 'contact-form-processor.zip'
      AutoPublishAlias: !Ref Stage
      Description: Sends an email of a contact form submission.
      MemorySize: 128
      Timeout: 5
      Role: !GetAtt ContactFunctionRole.Arn
      Tracing: Active
  ContactFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              -
                sts:AssumeRole
      ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
          - 'arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess'
      Policies:
        -
          PolicyName: ContactFunctionSesPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  -
                    ses:SendEmail
                Resource:
                  -
                    '*'
